---
name: Bug Report
about: Found a bug/issue with the bot? Use this template to file bug reports.
title: "[BUG] "
labels: 't: bug'
assignees: ''

---

**Describe The Bug**
Please give a clear, full description of the bug.

**Steps To Reproduce**
Please give a clear, full list of steps to reproduce the bug, if applicable. 

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional Information**
Please include any additional information you feel could help explain the bug/problem and get it resolved.
